require( 'sinatra' )
require( 'sinatra/contrib/all' )
require( 'pry-byebug' )
require_relative('controllers/add_controller')
require_relative('controllers/list_controller')
require_relative('controllers/show_controller')
require_relative('controllers/category_controller')
require_relative('controllers/budget_controller')
also_reload( '../models/*' )
